INSERT INTO mpa_rates (NAME) SELECT 'G' WHERE NOT EXISTS ( SELECT NAME FROM mpa_rates WHERE NAME = 'G' );
INSERT INTO mpa_rates (NAME) SELECT 'PG' WHERE NOT EXISTS ( SELECT NAME FROM mpa_rates WHERE NAME = 'PG' );
INSERT INTO mpa_rates (NAME) SELECT 'PG-13' WHERE NOT EXISTS ( SELECT NAME FROM mpa_rates WHERE NAME = 'PG-13' );
INSERT INTO mpa_rates (NAME) SELECT 'R' WHERE NOT EXISTS ( SELECT NAME FROM mpa_rates WHERE NAME = 'R' );
INSERT INTO mpa_rates (NAME) SELECT 'NC-17' WHERE NOT EXISTS ( SELECT NAME FROM mpa_rates WHERE NAME = 'NC-17' );

INSERT INTO genres (NAME) SELECT 'Комедия' WHERE NOT EXISTS ( SELECT NAME FROM genres WHERE NAME = 'Комедия' );
INSERT INTO genres (NAME) SELECT 'Драма' WHERE NOT EXISTS ( SELECT NAME FROM genres WHERE NAME = 'Драма' );
INSERT INTO genres (NAME) SELECT 'Мультфильм' WHERE NOT EXISTS ( SELECT NAME FROM genres WHERE NAME = 'Мультфильм' );
INSERT INTO genres (NAME) SELECT 'Триллер' WHERE NOT EXISTS ( SELECT NAME FROM genres WHERE NAME = 'Триллер' );
INSERT INTO genres (NAME) SELECT 'Документальный' WHERE NOT EXISTS ( SELECT NAME FROM genres WHERE NAME = 'Документальный' );
INSERT INTO genres (NAME) SELECT 'Боевик' WHERE NOT EXISTS ( SELECT NAME FROM genres WHERE NAME = 'Боевик' );
